#!/bin/sh

echo "BiliBili直播间瓜子领取机
Writen By esterTion"

function calcsign(){
  sign=$(echo -n "$1" | md5sum); sign=${sign:0:32}
}
function gettime(){
	time=$(date +%s)
}
ua="User-Agent: bilianime/2640 CFNetwork/711.1.12 Darwin/14.0.0"
if [[ $1 == "" ]]; then echo "请输入AccessKey"; exit; fi
access=$1

curl -L -s "http://live.bilibili.com/sign/doSign?access_key=$access"

function getstatus(){
echo -n "获取当前状态..."
gettime
calcsign "access_key=${access}&actionKey=appkey&appkey=27eb53fc9058f8c3&build=2640&device=pad&platform=ios&ts=${time}c2ed53a74eeefe3cf99fbd01d8c9c375"
url="http://live.bilibili.com/mobile/freeSilverCurrentTask?access_key=${access}&actionKey=appkey&appkey=27eb53fc9058f8c3&build=2640&device=pad&platform=ios&ts=$time&sign=$sign"
return=$(curl -L -s -H "$ua" "$url")
if [[ "$return" == "${return#\{}" || "$return" == "${return%\}}" ]]; then echo "获取出错，重试..."; sleep 3; getstatus; fi
if [[ "$return" != "${return#*code??-101}" ]]; then echo "AccessKey无效，请确认"; exit; fi
if [[ "$return" != "${return#*code??-10017}" ]]; then echo "今日瓜子已经领完"; exit; fi
waittime=${return#*minute\"\:}
until [[ $waittime == ${waittime%,*} ]]; do waittime=${waittime%,*}; done
silver=${return#*silver\"\:}
until [[ $silver == ${silver%,*} ]]; do silver=${silver%,*}; done
echo "完成
--------------------
本次需等待${waittime}分钟，可领取${silver}瓜子"
gettime
let "timeleft=waittime*60" goaltime=time+timeleft
timer
}

function timer(){
while (( $timeleft > 0 )); do
  let timeleft-- min=0 sec=timeleft
  while (( $sec > 59 )); do
    let min++ sec=sec-60
  done
  if (( $sec < 10 )); then sec=0$sec; fi
  echo -ne "\r剩余${min}分${sec}秒"
  sleep 1
done
getreward
}

function getreward(){
	echo -ne "\n\n领取瓜子..."
	done=
	until [[ $done == "done" ]]; do
	gettime
	calcsign "access_key=${access}&actionKey=appkey&appkey=27eb53fc9058f8c3&build=2640&device=pad&platform=ios&ts=${time}c2ed53a74eeefe3cf99fbd01d8c9c375"
	url="http://live.bilibili.com/mobile/freeSilverAward?access_key=${access}&actionKey=appkey&appkey=27eb53fc9058f8c3&build=2640&device=pad&platform=ios&ts=$time&sign=$sign"
	return=$(curl -L -s -H "$ua" "$url")
	if [[ "$return" != "${return#*message???ok}" ]]; then done=done; else echo -ne "\r领取瓜子出错，重试..."; echo $return; sleep 2; fi
	done
	echo "领取完成"
	if [[ "$return" != "${return#*isEnd??1}" ]]; then echo "今日瓜子领取结束，退出"; exit; fi
	getstatus
}
getstatus
